pull_request_rules:
  - name: Automatic merge on review
    # https://doc.mergify.io/examples.html#require-all-requested-reviews-to-be-approved
    conditions:
      - "#approved-reviews-by>=4"
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=approval + 3
    actions:
      merge:
        method: merge
      delete_head_branch: {}

  - name: Add Label needs author response
    conditions:
      - "#changes-requested-reviews-by>=1"
    actions:
      label:
        add: ["needs author response"]
        remove: ["needs review"]

  - name: Remove Label needs author response
    conditions:
      - "#changes-requested-reviews-by=0"
    actions:
      label:
        add: ["needs review"]
        remove: ["needs author response"]

  - name: Add Label approval + 1
    conditions:
      - "#approved-reviews-by=1"
    actions:
      label:
        add: ["approval + 1"]

  - name: Add Label approval + 2
    conditions:
      - "#approved-reviews-by=2"
    actions:
      label:
        add: ["approval + 2"]
        remove: ["approval + 1"]
  - name: Add Label approval + 3
    conditions:
      - "#approved-reviews-by=3"
    actions:
      label:
        add: ["approval + 3"]
        remove: ["approval + 2"]
