name: "Pull Request Action"
on: 
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create link
      uses: Im-D/Im-Bot/packages/pr-supporter/dist@master
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Create reviewRequest
      uses: Im-D/Im-Bot/packages/pr-reviewer/dist@master
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Link at README file
      uses: Im-D/Im-Bot/packages/update-readme/dist@master
      with:
        myToken: ${{ secrets.GITHUB_TOKEN}}
        linkLocTarget: '### 📅 History'
